manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/egevirgen

  #
  # Please add items below based on alphabetical order
  projects:
    - name: app
      revision: 81ade5a872a1975949905dd367a3a4d08755ac09
      path: Compile/app
    - name: mcrt
      revision: f70e2cae07361eeb3a28a223761a3f3e83d3cf2a
      path: Compile/mcrt
    - name: CANopenNode
      revision: 8c7d852902b2d307e8b91a43332c14e366641e00
      path: Compile/mcrt/communication/canopen/canopennode

  self:
    path: Compile
    west-commands: scripts/west-commands.yml
